apiVersion: v1
kind: Secret
metadata:
    name: project-secret
    namespace: project
stringData:
    DB_URL: ENC[AES256_GCM,data:F/w12ov/YkQrNMepg+io0HiASlywCAb5S/WV69CHQQo+LZCipDB38o8VaWQDNhTapQoBJzZWljoaa4CvCnBhBoGKzq0bjmrdkx5bpLG6NVHywfnyDCtrmg==,iv:XAw+MN93sYDds4KXP1GGYkxSvwDBWmYwzwirOpE0GCU=,tag:4HvAQwTOpuZLkn/xiYaxZw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:cp/BY4PmGDo=,iv:SMQFKLjAveXkl3OUs6JPvZPNx1xlyUM2cP0sczC+uDk=,tag:fPHj5BOdTqMhpRkolYGUsw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/oQaOG+r66/OAqFF,iv:5NvNNxppG8nO1LOTwSW1Y/nIOBU7i/YwvoppU+Cv6ag=,tag:PRjaOm3Xja60S/YbP9v+Yg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:rOoQvUI4,iv:JxqgxowO41Tocr2p/DAy9UDPmFKCo8LaNj8DyVKLJQI=,tag:Vzio1F0FLJnphUb6BiH2tg==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:m/n6DAxTnjC9nxfCygK7rgiCMywUC05CZMRE5n0Pv0bcD1L/wQWs+Yo6+fndUw==,iv:Ges2X9puLprhmJUFWqWH020Za11Ilv4SfYuEa3WQVDU=,tag:VHvXdapV0v/D5omaZ/SvAg==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:492x8PyWLD0GDA==,iv:V/nybyLjN2aCq5wB+Ze+nVcST0E3DTk8VTStO2GmTE0=,tag:Zy+LyBudz93Ua6pXnZYRHQ==,type:str]
sops:
    age:
        - recipient: age1ekqjgmayst3ugq4fv405gts384l7jd4d4fqnpazxwg5v0vauwfjqa2x7pc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0L0VLaEppRlZGcmx2R1FE
            dTNacnd0M0hiUzVQYkx0QkplL1hTaHhUM3cwCnZUc2Z6WTJCTVp0TXd1ZWRCRFJt
            cyttUDFmNmlMcm9VeWZOOGpwSHg2aVUKLS0tIDFxbVIzdTdIMngxMTFWSmp1a2xV
            T01wemV2UjkwVzZIZm5MTTd6dTRFbGMKlRRUKUrTljZKUtIvIHkz1q02U/KNsWs1
            1kcSlPUsxCKcXTKVNKIcOSCxmvWgEXG5dkd58gVqQUwS10rLaCNpOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T12:57:49Z"
    mac: ENC[AES256_GCM,data:B4TjiudqRP5tmM5Sc9t0h260HC5gx7xxTWG6ZuGD4xm7r/mYFKLOLr8tkjzscaDu3Z6JtemSfiXCbY7Gd20ZSP73BNOorE3k6GgWHryAJXbUvJPjgm5KHvGe8d6uvsRvp23AXWw6qFoph8KTe1lMLLcglCJuxsJ28Z3f+aIhpdc=,iv:WMDBF3qPvKqs4HXoRJpRRmNUtNqrTQtzsASC23RbBf4=,tag:Yl14SQrwBiF3aNjdTlq/Hw==,type:str]
    encrypted_regex: (stringData)
    version: 3.11.0
