apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/kirillstrelkov/KubernetesSubmissions.git"
    targetRevision: HEAD
    path: the_project/kust-argocd/production
    plugin:
      name: "custom-argocd-cmp-sops"
  destination:
    server: https://kubernetes.default.svc # TODO: replace with GKE cluster server URL
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
