apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: restart-rate
spec:
  metrics:
    - name: restart-rate
      initialDelay: 2m
      successCondition: result < 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1764-prometheus.prometheus.svc.cluster.local:9090
          query: |
            scalar(
              sum(kube_pod_container_status_restarts_total{namespace="exercises", container="flaky-update"}) -
              sum(kube_pod_container_status_restarts_total{namespace="exercises", container="flaky-update"} offset 2m)
            )
